"""monthly budget goals

Revision ID: 11ab62a0973b
Revises: 1badbfe4377b
Create Date: 2026-09-13 00:53:27.612510

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11ab62a0973b"
down_revision: str | Sequence[str] | None = "1badbfe4377b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monthly_budget_goals",
        sa.Column("month_start", sa.Date(), nullable=False),
        sa.Column("goal_cents", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM month_start) = 1",
            name=op.f("ck_monthly_budget_goals_month_start_is_first"),
        ),
        sa.CheckConstraint(
            "goal_cents >= 0", name=op.f("ck_monthly_budget_goals_goal_non_negative")
        ),
        sa.PrimaryKeyConstraint("month_start", name=op.f("pk_monthly_budget_goals")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monthly_budget_goals")
    # ### end Alembic commands ###
