"""transaction templates

Revision ID: 1badbfe4377b
Revises: bde912e155cc
Create Date: 2026-09-12 21:36:28.965595

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1badbfe4377b"
down_revision: str | Sequence[str] | None = "bde912e155cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_templates",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("merchant", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("subcategory", sa.String(length=50), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=True),
        sa.Column("payment_method_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "is_subscription",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_cents IS NULL OR amount_cents > 0",
            name=op.f("ck_transaction_templates_amount_positive_or_null"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_transaction_templates_payment_method_id_payment_methods"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_transaction_templates_name")),
    )
    op.create_index(
        op.f("ix_transaction_templates_payment_method_id"),
        "transaction_templates",
        ["payment_method_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transaction_templates_payment_method_id"),
        table_name="transaction_templates",
    )
    op.drop_table("transaction_templates")
    # ### end Alembic commands ###
