"""reimbursements

Revision ID: 49c2b29272c5
Revises: 11ab62a0973b
Create Date: 2026-09-13 01:11:06.819149

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49c2b29272c5"
down_revision: str | Sequence[str] | None = "11ab62a0973b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reimbursements",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "Company",
                "Family",
                "Refund",
                "Other",
                name="reimbursementsource",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "expected",
                "received",
                "cancelled",
                name="reimbursementstatus",
                native_enum=False,
            ),
            server_default="expected",
            nullable=False,
        ),
        sa.Column("received_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('Company', 'Family', 'Refund', 'Other')",
            name=op.f("ck_reimbursements_source_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'received' OR received_date IS NOT NULL",
            name=op.f("ck_reimbursements_received_needs_date"),
        ),
        sa.CheckConstraint(
            "status IN ('expected', 'received', 'cancelled')",
            name=op.f("ck_reimbursements_status_valid"),
        ),
        sa.CheckConstraint(
            "amount_cents > 0", name=op.f("ck_reimbursements_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_reimbursements_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reimbursements")),
    )
    op.create_index(
        op.f("ix_reimbursements_received_date"),
        "reimbursements",
        ["received_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reimbursements_transaction_id"),
        "reimbursements",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        "ix_reimbursements_transaction_id_status",
        "reimbursements",
        ["transaction_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_reimbursements_transaction_id_status", table_name="reimbursements"
    )
    op.drop_index(op.f("ix_reimbursements_transaction_id"), table_name="reimbursements")
    op.drop_index(op.f("ix_reimbursements_received_date"), table_name="reimbursements")
    op.drop_table("reimbursements")
    # ### end Alembic commands ###
