"""payment methods and transactions

Revision ID: bde912e155cc
Revises:
Create Date: 2026-09-12 19:30:48.418323

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bde912e155cc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "credit",
                "debit",
                "ach",
                "other",
                name="paymentmethodkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('credit', 'debit', 'ach', 'other')",
            name=op.f("ck_payment_methods_kind_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_methods")),
        sa.UniqueConstraint("name", name=op.f("uq_payment_methods_name")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("merchant", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("subcategory", sa.String(length=50), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("payment_method_id", sa.BigInteger(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "is_subscription",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("order_ref", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_cents > 0", name=op.f("ck_transactions_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name=op.f("fk_transactions_payment_method_id_payment_methods"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_index(
        "ix_transactions_category_subcategory",
        "transactions",
        ["category", "subcategory"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_order_ref"), "transactions", ["order_ref"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_payment_method_id"),
        "transactions",
        ["payment_method_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_txn_date"), "transactions", ["txn_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_txn_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_payment_method_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_order_ref"), table_name="transactions")
    op.drop_index("ix_transactions_category_subcategory", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
